name: nichecompass
channels:
  - bioconda
  - conda-forge
  - nvidia
dependencies:
  - python=3.9
  - jaxlib=*=*cuda*
  - jax=0.4.13
  - cuda-nvcc
  - pip
  - poetry=1.4.2
  - bedtools=2.30.0
  - geckodriver=0.33.0
  - pip:
    - ipykernel==6.15.3
    - ipywidgets==8.0.2
    - jupyterlab==3.4.7