name: autotalker
channels:
  - conda-forge
dependencies:
  - cudatoolkit=10.2
  - pip=22.2.2
  - python=3.9
  - pytorch=1.12.1
  - mlflow=1.27.0
  - pip:
    - squidpy==1.2.2
    - torch-scatter -f https://data.pyg.org/whl/torch-1.12.1+cu102.html
    - torch-sparse -f https://data.pyg.org/whl/torch-1.12.1+cu102.html
    - git+https://github.com/pyg-team/pytorch_geometric.git