name: nichecompass
channels:
  - bioconda
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - jax=0.4.13
  - poetry=1.4.2
  - bedtools=2.30.0
  - geckodriver=0.33.0
  - pip:
    - ipykernel==6.15.3
    - ipywidgets==8.0.2
    - jupyterlab==3.4.7