name: autotalker-dev
dependencies:
  - cudatoolkit=10.2
  - python=3.8.8
  - pytorch=1.12.1
  - mlflow=1.27.0
  - pip:
    - pip install squidpy==1.2.2
    - pip install torch-scatter -f https://data.pyg.org/whl/torch-1.12.1+cu102.html
    - pip install torch-sparse -f https://data.pyg.org/whl/torch-1.12.1+cu102.html
    - pip install torch-geometric==2.0.4