name: autotalker_cpu
channels:
  - conda-forge
  - bioconda
  - pytorch
dependencies:
  - bedtools=2.30.0
  - pip=22.2.2
  - python=3.9
  - pytorch=2.0.0
  - pip:
    - bokeh==2.4.3
    - holoviews==1.15.4
    - ipykernel==6.15.3
    - ipywidgets==8.0.2
    - jupyterlab==3.4.7
    - mlflow==1.28.0
    - pyreadr==0.4.6
    - selenium==4.8.2
    - scib==1.1.1
    - scikit-misc==0.1.4
    - squidpy==1.2.2
    - torch-geometric==2.1.0post1
    - torch-scatter==2.1.1
    - -f https://data.pyg.org/whl/torch-2.0.0+cpu.html
    - torch-sparse==0.6.17
    - -f https://data.pyg.org/whl/torch-2.0.0+cpu.html