name: autotalker
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nvidia
dependencies:
  - bedtools=2.30.0
  - pip=23.0.1
  - python=3.9
  - pip:
    - bokeh==2.4.3
    - holoviews==1.15.4
    - ipykernel==6.15.3
    - ipywidgets==8.0.2
    - jupyterlab==3.4.7
    - mlflow==1.28.0
    - pyreadr==0.4.6
    - selenium==4.8.2
    - scib==1.1.1
    - scikit-misc==0.1.4
    - scglue==0.3.2
    - squidpy==1.2.2
    - torch==2.0.0
    - --index-url https://download.pytorch.org/whl/cu117
    - torch-geometric==2.1.0post1
    - torch-scatter==2.1.1
    - -f https://data.pyg.org/whl/torch-2.0.0+cu117.html
    - torch-sparse==0.6.17
    - -f https://data.pyg.org/whl/torch-2.0.0+cu117.html