name: autotalker
channels:
  - pytorch
dependencies:
  - cudatoolkit=11.3.1
  - pip=22.2.2
  - python=3.9
  - pytorch=1.12.1
  - pip:
    - ipykernel==6.15.3
    - ipywidgets==8.0.2
    - jupyterlab==3.4.7
    - mlflow==1.28.0
    - pyreadr==0.4.6
    - scib==1.1.1
    - scikit-misc==0.1.4
    - squidpy==1.2.2
    - torch-geometric==2.1.0.post1
    - torch-scatter==2.0.9
    - -f https://data.pyg.org/whl/torch-1.12.1+cu113.html
    - torch-sparse==0.6.15
    - -f https://data.pyg.org/whl/torch-1.12.1+cu113.html